name: bus_trackr
description: A prototype for a bus tracking mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mqtt_client: ^9.8.1
  typed_data: ^1.3.1
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.2.6
  get_it: ^7.4.1
  dartz: ^0.10.1
  mapbox_gl: ^0.16.0
  geolocator: ^9.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  font_awesome_flutter: ^10.4.0
  flutter_local_notifications: ^14.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/certificates/
    - .env
